AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

FactoryBot/CreateList:
  AutoCorrect: true

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

# Disable problematic cops that are causing errors
Capybara/RSpec/PredicateMatcher:
  Enabled: false

require:
  - rubocop-rspec